### ISSUE TITLE
scrapyd-deploy doesn't paste *.txt and other file to *.egg file

### ISSUE THREAD

**Issue by amarynets** [scrapy/scrapyd-client#48] opened 2017-08-30 11:42 UTC
When I run `scrapyd-deploy project -p project` this command doesn't copy `.txt` file to egg archive. If I change the extension from `.txt` to `.py` all works fine. How can I fix it?

**Comment by kmike** [comment] 2017-08-30 11:49
@amarynets you can modify setup.py to include data files - use `package_data` setup option.

**Comment by amarynets** [comment] 2017-08-30 11:52
@kmike Thanks. My issue was similar to #46

**Comment by kmike** [comment] 2017-08-30 17:18
A good catch! 
I'm closing it as a duplicate of #46.

**Closed by kmike** 2017-08-30 17:18 UTC
Labels: duplicate
